public static class GameEvent {
	public const string SPEED_SLIDER_CHANGED = "SPEED_SLIDER_CHANGED";
	public const string PLAYER_INITIATED_GAME = "PLAYER_INITIATED_GAME";
	public const string PLAYER_GOT_TEN_PASSES = "PLAYER_GOT_TEN_PASSES";
	public const string RAN_STOP_SIGN = "RAN_STOP_SIGN";
	public const string STOP_SIGN_ARRIVAL = "STOP_SIGN_ARRIVAL";
	public const string NPC_SAW_OTHER_NPC = "NPC_SAW_OTHER_NPC";
	public const string APPROACHING_ONCOMING_TRAFFIC = "APPROACHING_ONCOMING_TRAFFIC";
	public const string ENCOUNTERED_STOP_SIGN = "ENCOUNTERED_STOP_SIGN";
	public const string APPROACHING_STOP_SIGN = "APPROACHING_STOP_SIGN";
	public const string CHRACTER_STARTED_SPEEDING = "CHARACTER_STARTED_SPEEDING";
}